Fix extended line with \

diff --git a/config/Dockerfiles/sample-fail-container/Dockerfile b/config/Dockerfiles/sample-fail-container/Dockerfile
--- a/config/Dockerfiles/sample-fail-container/Dockerfile
+++ b/config/Dockerfiles/sample-fail-container/Dockerfile
@@ -24,11 +24,11 @@ RUN for i in {1..5} ; do dnf -y install ansible \
 COPY opt-test.sh /tmp/opt-test.sh
 
 # Fail image build if FAIL_IT = true
-RUN if [ "${FAIL_IT}" == "true" ]; then
-        echo "FAIL_IT: true";
-        exit 1;
-    else
-        echo "FAIL_IT: false";
+RUN if [ "${FAIL_IT}" == "true" ]; then \
+        echo "FAIL_IT: true"; \
+        exit 1; \
+    else \
+        echo "FAIL_IT: false"; \
     fi
 
 # Run the build script
